/* @flow */

export const ActionStates = {
  REQUEST: '_REQUEST',
  FAIL: '_FAIL',
  COMPLETE: '_COMPLETE',
};

export const ABOUT_FETCH = 'ABOUT_FETCH';

export const ACCOUNT_SIGNUP = 'ACCOUNT_SIGNUP';
// export const ACCOUNT_SIGNUP_FORM_RESET = 'ACCOUNT_SIGNUP_FORM_RESET';
// export const ACCOUNT_SIGNUP_FORM_ITEM_SET = 'ACCOUNT_SIGNUP_FORM_ITEM_SET';
// export const ACCOUNT_SIGNUP_FORM_STATE_SET = 'ACCOUNT_SIGNUP_FORM_STATE_SET';
// export const ACCOUNT_SIGNUP_FORM_STATUS_SET = 'ACCOUNT_SIGNUP_FORM_STATUS_SET';
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
// export const ACCOUNT_LOGIN_FORM_RESET = 'ACCOUNT_LOGIN_FORM_RESET';
// export const ACCOUNT_LOGIN_FORM_ITEM_SET = 'ACCOUNT_LOGIN_FORM_ITEM_SET';
// export const ACCOUNT_LOGIN_FORM_STATE_SET = 'ACCOUNT_LOGIN_FORM_STATE_SET';
// export const ACCOUNT_LOGIN_FORM_STATUS_SET = 'ACCOUNT_LOGIN_FORM_STATUS_SET';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_USER_FETCH = 'ACCOUNT_USER_FETCH';

export const CONTACTUS_MAIL_SEND = 'CONTACTUS_MAIL_SEND';

export const TODOS_FETCH = 'TODOS_FETCH';
export const TODO_SET = 'TODO_SET';
export const TODO_DELETE = 'TODO_DELETE';
export const TODO_ADD = 'TODO_ADD';

export const CHARGE_ITEM_FETCH = 'CHARGE_ITEM_FETCH';
export const CHARGE_ITEM_CREATE = 'CHARGE_ITEM_CREATE';
export const CHARGE_ITEM_EDIT = 'CHARGE_ITEM_EDIT';
export const CHARGE_ITEM_EDIT_SET = 'CHARGE_ITEM_EDIT_SET';
export const CHARGE_ITEM_EDIT_RESET = 'CHARGE_ITEM_EDIT_RESET';
export const CHARGE_ITEM_SELECTED_SET = 'CHARGE_ITEM_SELECTED_SET';

export const CHARGE_TYPE_ITEM_FETCH = 'CHARGE_TYPE_ITEM_FETCH';
export const CHARGE_TYPE_ITEM_EDIT = 'CHARGE_TYPE_ITEM_EDIT';
export const CHARGE_TYPE_ITEM_REMOVAL = 'CHARGE_TYPE_ITEM_REMOVAL';

export const FORM_ERROR_SET = 'FORM_ERROR_SET';

export const INTL_LOCALE_SET = 'INTL_LOCALE_SET';
export const INTL_SET = 'INTL_SET';

export default module.exports;
